---
title: Erikeldridge.Github.Com
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: "/notes/:title.html"
highlighter: pygments
markdown: kramdown
kramdown:
  toc_levels: 2..5
sass:
  style: compressed
