---
exclude: ['new.sh']
title: erikeldridge.com
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
gems:
- jekyll-seo-tag
permalink: "/notes/:title.html"
highlighter: pygments
markdown: kramdown
kramdown:
  toc_levels: 2..5
sass:
  style: compressed
