---
title: erikeldridge.com
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
exclude:
- new.rb
- nlp
- README.md
- src
plugins:
- jekyll-feed
- jekyll-gist
- jekyll-seo-tag
gist:
  noscript: false
permalink: "/notes/:title.html"
markdown: kramdown
kramdown:
  toc_levels: 2..5
  # Smart quotes complicate stop word filtering, so disable.
  smart_quotes: ["apos", "apos", "quot", "quot"]
sass:
  style: compressed
