---
title: erikeldridge.com
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
exclude:
- new.rb
- nlp
- README.md
- node_modules
- package-lock.json
- build-search-index.js
plugins:
- jekyll-gist
- jekyll-seo-tag
gist:
  noscript: false
permalink: "/notes/:title.html"
markdown: kramdown
kramdown:
  toc_levels: 2..5
sass:
  style: compressed
