title = "erikeldridge.com"

# Support custom domain
baseURL = "https://erikeldridge.com"

# I like to colocate the Obsidian template
# directory with the .obsidian directory,
# but the template directory can't be hidden,
# so I ignore it explicitly.
ignoreFiles = ['/_obsidian-templates/']

# As recommended by
# https://gohugo.io/host-and-deploy/host-on-github-pages/#step-3
[caches]
  [caches.images]
    dir = ':cacheDir/images'

